#:kivy 2.3.1

#:import SG lammlot.sticker_generator.StickerGenerator


<StickerScreen>:
    id: sticker_screen
    name: 'sticker'

    ScrollView:
        do_scroll_x: False

        StackLayout:
            id: stickers
            padding: 30
            spacing: 30

    CloseButton:
        on_press: root.manager.current = 'search'

    Button:
        pos_hint: {'bottom': 0, 'right': 1}
        size_hint: None, 0.05
        text: 'Save'
        on_press: sticker_screen.save_images()