#:kivy 2.3.1


<StickerSizeButton@ToggleButton>:
    text: f"{self.sticker_size[0]}x{self.sticker_size[1]}mm" if self.screen else "size"
    group: "sticker_sizes"
    state: "down" if self.screen and self.sticker_size == self.screen.sticker_size else "normal"
    on_press: self.screen.set_sticker_size(self.sticker_size)
    sticker_size: [10, 10]
    size_hint_x: None
    width: 140
    allow_no_selection: False # Make into radio button.
    screen: None
